### ISSUE TITLE
Strange panel on iOS in landscape mode

### ISSUE THREAD

**Issue by ljudbane** [alan-ai/alan-sdk-ionic#49]
We have noticed that when our app is in landscape mode, a strange panel shows up on left side of the screen. The panel only shows when Alan button in enabled. I've attached screenshots. The panel can be scrolled a bit and it shows an animation of a dog in the top part. This only happens on iOS in simulator and on devices. It's not part of webview, but 'overlays' it.

Could this be some part of your SDK or libraries? I can't find the origin of the panel, but it's consistent with the fact that it only shows when Alan button is visible. 

![Simulator Screen Shot - iPhone 11 - 2022-03-11 at 16 13 55](https://user-images.githubusercontent.com/25686317/157896156-a509fd5f-1eae-4171-a5c9-ee934baf6d9c.png)

![Screenshot 2022-03-11 at 16 16 01](https://user-images.githubusercontent.com/25686317/157896187-da67a3e1-a548-4551-9953-60a66222fc84.png)

**Comment by snyuryev** [comment]
@ljudbane I can suggest to revert back to previous version of plugin at this moment. 

And ww will release an update on begging of next week for this issue.

**Comment by snyuryev** [comment]
@ljudbane 

New version is published (https://www.npmjs.com/package/@alan-ai/cordova-plugin-alan-voice/v/2.5.0)
Please try it.

**Comment by ljudbane** [comment]
I've tested with version 2.5.0 and the panel is no longer present. I'm closing this issue.
